"""Model Context Protocol (MCP) server for a persistent HippoRAG index.

Run ``hipporag-mcp --save_dir <dir>`` (stdio, for local MCP clients) or add
``--transport streamable-http`` to serve over HTTP. Requires ``pip install 'hipporag[mcp]'``.
"""
import argparse
import asyncio
import json
import logging
import sys
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager
from dataclasses import asdict, fields
from typing import Annotated, Any, Callable, Dict, List, Optional, Sequence, TypeVar, Union

from pydantic import BaseModel, Field

try:
    from mcp.server.mcpserver import MCPServer
    from mcp.server.mcpserver.exceptions import ToolError
    from mcp.types import ToolAnnotations
except ImportError as exc:  # pragma: no cover - depends on the optional extra
    raise ImportError(
        "The HippoRAG MCP server requires the optional 'mcp' dependency (mcp>=2.2,<3). "
        "Install it with: pip install 'hipporag[mcp]'"
    ) from exc

from .utils.config_utils import BaseConfig
from .utils.logging_utils import redact_config
from .utils.misc_utils import Chunk

logger = logging.getLogger(__name__)

T = TypeVar("T")

MAX_TOP_K = 100

SERVER_INSTRUCTIONS = """\
HippoRAG is a graph-based long-term memory for documents. It extracts a knowledge graph from indexed
passages and retrieves with Personalized PageRank, which helps with multi-hop questions whose answer
spans several passages.

- `retrieve` returns the most relevant passages for a query; use it to gather evidence and cite sources.
- `rag_qa` retrieves passages and has the server-side LLM answer the question from them.
- `index` adds documents (one LLM extraction pass per new passage; re-indexing an existing passage is a no-op).
- `delete` removes passages by exact text (as returned by `retrieve`) or by the `source_id` given at indexing time.
- `index_stats` reports the size of the index.
The index persists on disk across server restarts.
"""


class DocumentInput(BaseModel):
    """A document with optional provenance, kept with each passage and returned by retrieval."""
    text: str = Field(min_length=1, description="Document text.")
    source_id: Optional[str] = Field(default=None, description="Stable identifier of the source, e.g. a URL or file path. Can be used to delete the document later.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary JSON metadata returned with retrieved passages.")


class Passage(BaseModel):
    rank: int = Field(description="1-based rank.")
    text: str
    score: float = Field(description="Retrieval score; only comparable within one response.")
    source_id: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class RetrieveResult(BaseModel):
    query: str
    passages: List[Passage]


class QAResult(BaseModel):
    question: str
    answer: str = Field(description="Answer generated by the server-side LLM from the passages below.")
    passages: List[Passage] = Field(description="Passages the answer was generated from.")


class IndexResult(BaseModel):
    documents_received: int
    passages_added: int = Field(description="New passages; documents already in the index are not re-added.")
    total_passages: int


class DeleteResult(BaseModel):
    passages_deleted: int
    not_found: List[str] = Field(description="Requested texts or source_ids that matched no indexed passage.")
    total_passages: int


class IndexStats(BaseModel):
    passages: int
    entities: int
    facts: int
    graph_nodes: int
    graph_edges: int
    working_dir: str
    llm_name: str
    embedding_model_name: str
    read_only: bool


def _to_chunk(document: Union[str, DocumentInput]) -> Chunk:
    if isinstance(document, str):
        if not document.strip():
            raise ToolError("Documents must not be empty.")
        return Chunk(content=document)
    if not document.text.strip():
        raise ToolError("Documents must not be empty.")
    return Chunk(content=document.text, source_id=document.source_id, metadata=dict(document.metadata))


def _passages(docs: Sequence[str], scores, metadata: Optional[Sequence[Dict[str, Any]]]) -> List[Passage]:
    passages = []
    for idx, text in enumerate(docs):
        item_metadata = dict(metadata[idx]) if metadata and idx < len(metadata) else {}
        source_id = item_metadata.pop("source_id", None)
        score = float(scores[idx]) if scores is not None and idx < len(scores) else 0.0
        passages.append(Passage(rank=idx + 1, text=text, score=score, source_id=source_id, metadata=item_metadata))
    return passages


def _num_passages(rag) -> int:
    return len(rag.chunk_embedding_store.get_all_ids())


def _require_nonempty_index(rag) -> None:
    if _num_passages(rag) == 0:
        raise ToolError("The index is empty. Add documents with the `index` tool first.")


def index_documents(rag, documents: Sequence[Union[str, DocumentInput]]) -> IndexResult:
    chunks = [_to_chunk(document) for document in documents]
    before = _num_passages(rag)
    rag.index(chunks)
    after = _num_passages(rag)
    return IndexResult(documents_received=len(chunks), passages_added=after - before, total_passages=after)


def delete_documents(rag, texts: Optional[Sequence[str]], source_ids: Optional[Sequence[str]]) -> DeleteResult:
    if not texts and not source_ids:
        raise ToolError("Provide `texts` and/or `source_ids` to delete.")
    store = rag.chunk_embedding_store
    indexed_ids = set(store.get_all_ids())
    to_delete = set()
    not_found = []
    for text in texts or []:
        if text in store.text_to_hash_id and store.text_to_hash_id[text] in indexed_ids:
            to_delete.add(text)
        else:
            not_found.append(text)
    for source_id in source_ids or []:
        matches = [chunk_id for chunk_id in indexed_ids if rag.chunk_metadata.get(chunk_id, {}).get("source_id") == source_id]
        if not matches:
            not_found.append(source_id)
        to_delete.update(store.get_row(chunk_id)["content"] for chunk_id in matches)
    before = len(indexed_ids)
    if to_delete:
        rag.delete(sorted(to_delete))
    after = _num_passages(rag)
    return DeleteResult(passages_deleted=before - after, not_found=not_found, total_passages=after)


def retrieve_passages(rag, query: str, top_k: int) -> RetrieveResult:
    _require_nonempty_index(rag)
    solution = rag.retrieve([query], num_to_retrieve=top_k)[0]
    return RetrieveResult(query=query, passages=_passages(solution.docs, solution.doc_scores, solution.doc_metadata))


def answer_question(rag, question: str) -> QAResult:
    _require_nonempty_index(rag)
    solutions, _, _ = rag.rag_qa([question])
    solution = solutions[0]
    qa_top_k = rag.global_config.qa_top_k
    passages = _passages(solution.docs[:qa_top_k], solution.doc_scores, solution.doc_metadata)
    return QAResult(question=question, answer=solution.answer or "", passages=passages)


def index_stats(rag, read_only: bool) -> IndexStats:
    return IndexStats(
        passages=_num_passages(rag),
        entities=len(rag.entity_embedding_store.get_all_ids()),
        facts=len(rag.fact_embedding_store.get_all_ids()),
        graph_nodes=rag.graph.vcount(),
        graph_edges=rag.graph.ecount(),
        working_dir=rag.working_dir,
        llm_name=rag.global_config.llm_name,
        embedding_model_name=rag.global_config.embedding_model_name,
        read_only=read_only,
    )


class HippoRAGService:
    """Owns one HippoRAG instance and runs every operation on a single worker thread.

    HippoRAG is not thread-safe, so tool calls are serialized; running them off the event loop keeps
    the MCP session responsive while a long indexing call is in progress.
    """

    def __init__(self, factory: Callable[[], Any]):
        self._factory = factory
        self._rag = None
        self._executor: Optional[ThreadPoolExecutor] = None

    def _get(self):
        if self._rag is None:
            self._rag = self._factory()
        return self._rag

    def _warm_up(self) -> None:
        try:
            self._get()
        except Exception:
            logger.exception("Failed to initialize HippoRAG; the error will be reported on the first tool call.")

    def start(self) -> None:
        """Begins loading models and index state in the background."""
        if self._executor is None:
            self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="hipporag")
        self._executor.submit(self._warm_up)

    async def run(self, fn: Callable[[Any], T]) -> T:
        def job():
            return fn(self._get())

        if self._executor is None:
            raise ToolError("The HippoRAG service is not running.")
        try:
            return await asyncio.wrap_future(self._executor.submit(job))
        except ToolError:
            raise
        except Exception as exc:
            logger.exception("HippoRAG operation failed")
            raise ToolError(f"{type(exc).__name__}: {exc}") from exc

    def close(self) -> None:
        def close_rag():
            if self._rag is not None:
                self._rag.close()
                self._rag = None

        executor, self._executor = self._executor, None
        if executor is None:
            return
        try:
            executor.submit(close_rag).result()
        finally:
            executor.shutdown(wait=True)


def create_server(service: HippoRAGService, config: BaseConfig, read_only: bool = False) -> MCPServer:
    """Builds the MCP server around a service; `config` is only used for the config resource."""

    @asynccontextmanager
    async def lifespan(_server):
        service.start()
        try:
            yield {}
        finally:
            await asyncio.get_running_loop().run_in_executor(None, service.close)

    server = MCPServer(
        name="hipporag",
        title="HippoRAG",
        instructions=SERVER_INSTRUCTIONS,
        lifespan=lifespan,
    )

    @server.tool(
        title="Retrieve passages",
        annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False),
    )
    async def retrieve(
        query: Annotated[str, Field(min_length=1, description="Natural-language query.")],
        top_k: Annotated[int, Field(ge=1, le=MAX_TOP_K, description="Number of passages to return.")] = 5,
    ) -> RetrieveResult:
        """Retrieve the passages most relevant to a query using HippoRAG's knowledge-graph retrieval."""
        return await service.run(lambda rag: retrieve_passages(rag, query, top_k))

    @server.tool(
        title="Answer a question",
        annotations=ToolAnnotations(read_only_hint=True, open_world_hint=True),
    )
    async def rag_qa(
        question: Annotated[str, Field(min_length=1, description="Question to answer from the indexed documents.")],
    ) -> QAResult:
        """Answer a question with the server-side LLM, grounded in passages retrieved by HippoRAG."""
        return await service.run(lambda rag: answer_question(rag, question))

    @server.tool(
        name="index_stats",
        title="Index statistics",
        annotations=ToolAnnotations(read_only_hint=True, open_world_hint=False),
    )
    async def index_stats_tool() -> IndexStats:
        """Report the number of passages, entities, facts and graph elements in the index."""
        return await service.run(lambda rag: index_stats(rag, read_only))

    if not read_only:
        @server.tool(
            title="Index documents",
            annotations=ToolAnnotations(read_only_hint=False, destructive_hint=False, idempotent_hint=True, open_world_hint=True),
        )
        async def index(
            documents: Annotated[
                List[Union[str, DocumentInput]],
                Field(min_length=1, description="Documents to add, as plain strings or objects with text, source_id and metadata."),
            ],
        ) -> IndexResult:
            """Add documents to the persistent index. Each new passage costs one LLM extraction pass; existing passages are skipped."""
            return await service.run(lambda rag: index_documents(rag, documents))

        @server.tool(
            title="Delete documents",
            annotations=ToolAnnotations(read_only_hint=False, destructive_hint=True, idempotent_hint=True, open_world_hint=False),
        )
        async def delete(
            texts: Annotated[Optional[List[str]], Field(description="Exact passage texts to delete, as returned by `retrieve`.")] = None,
            source_ids: Annotated[Optional[List[str]], Field(description="Delete every passage indexed with one of these source_ids.")] = None,
        ) -> DeleteResult:
            """Delete passages from the index by exact text or by source_id."""
            return await service.run(lambda rag: delete_documents(rag, texts, source_ids))

    @server.resource("hipporag://config", name="config", title="HippoRAG configuration", mime_type="application/json")
    def config_resource() -> str:
        """The active HippoRAG configuration, with secrets redacted."""
        return json.dumps(redact_config(asdict(config)), indent=2, default=str)

    return server


_CONFIG_FIELDS = {f.name for f in fields(BaseConfig)}

# CLI flags that map one-to-one onto BaseConfig fields.
_CONFIG_FLAGS = {
    "save_dir": "Directory holding the persistent index (created if missing).",
    "llm_name": "LLM used for OpenIE extraction and QA.",
    "llm_base_url": "Base URL of an OpenAI-compatible LLM endpoint.",
    "llm_api_key_env": "Environment variable holding the LLM API key (default OPENAI_API_KEY).",
    "embedding_model_name": "Embedding model name.",
    "embedding_base_url": "Base URL of an OpenAI-compatible embedding endpoint.",
    "embedding_api_key_env": "Environment variable holding the embedding API key (default OPENAI_API_KEY).",
    "embedding_provider": "Embedding provider, e.g. openai or transformers.",
    "azure_endpoint": "Azure OpenAI resource endpoint for the LLM.",
    "azure_embedding_endpoint": "Azure OpenAI resource endpoint for embeddings.",
}


def _parse_config_override(item: str):
    key, sep, raw_value = item.partition("=")
    key = key.strip()
    if not sep or not key:
        raise argparse.ArgumentTypeError(f"Expected KEY=VALUE, got {item!r}.")
    if key not in _CONFIG_FIELDS:
        raise argparse.ArgumentTypeError(f"Unknown BaseConfig field {key!r}.")
    try:
        value = json.loads(raw_value)
    except json.JSONDecodeError:
        value = raw_value
    return key, value


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hipporag-mcp",
        description="Serve a persistent HippoRAG index over the Model Context Protocol.",
    )
    for name, help_text in _CONFIG_FLAGS.items():
        parser.add_argument(f"--{name}", required=name == "save_dir", help=help_text)
    parser.add_argument(
        "--config", action="append", default=[], type=_parse_config_override, metavar="KEY=VALUE",
        help="Set any other BaseConfig field; VALUE is parsed as JSON when possible. Repeatable.",
    )
    parser.add_argument("--read_only", action="store_true", help="Expose only retrieval tools; disable index and delete.")
    parser.add_argument("--transport", choices=["stdio", "streamable-http"], default="stdio")
    parser.add_argument("--host", default="127.0.0.1", help="Host for streamable-http.")
    parser.add_argument("--port", type=int, default=8000, help="Port for streamable-http.")
    parser.add_argument("--log_level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    return parser


def build_config(args: argparse.Namespace) -> BaseConfig:
    overrides = {name: getattr(args, name) for name in _CONFIG_FLAGS if getattr(args, name) is not None}
    for key, value in args.config:
        if key in overrides and overrides[key] != value:
            raise ValueError(f"{key} is set both as a flag and through --config.")
        overrides[key] = value
    config = BaseConfig(**overrides)
    config.validate()
    return config


def main(argv: Optional[Sequence[str]] = None) -> None:
    args = build_arg_parser().parse_args(argv)
    # Logs must go to stderr: with the stdio transport, stdout carries the protocol.
    logging.basicConfig(level=args.log_level, stream=sys.stderr, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    try:
        config = build_config(args)
    except (TypeError, ValueError) as exc:
        sys.exit(f"hipporag-mcp: invalid configuration: {exc}")

    def factory():
        from .HippoRAG import HippoRAG
        return HippoRAG(global_config=config)

    server = create_server(HippoRAGService(factory), config, read_only=args.read_only)
    if args.transport == "stdio":
        server.run("stdio")
    else:
        if args.host not in ("127.0.0.1", "localhost", "::1") and not args.read_only:
            logger.warning("Serving index and delete tools without authentication on %s; consider --read_only or an authenticating proxy.", args.host)
        server.run("streamable-http", host=args.host, port=args.port)


if __name__ == "__main__":
    main()
